{% set name = "urchin" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fishbotics/urchin/archive/refs/tags/v{{ version }}.zip
  sha256: cca32a41634ca951c89e296d0dee309f058187e5d1a6c867fa36a33fe2aa21ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh

test:
  imports:
    - urchin
  commands:
    - pip check
  requires:
    - pip
    - libgl  # [linux]
    - python {{ python_min }}

about:
  home: https://github.com/fishbotics/urchin
  summary: URDF parser and manipulator for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
